# example: test GET /API/data/:id - status 404
GET http://localhost:3001/API/data/98239182398

#############################################

# test GET /API/data/:id - status OK

// continue here!

#############################################

# test GET /API/users - status OK

// continue here!

#############################################

# example: test UPDATE [1] /API/data/:id status OK
PUT http://localhost:3001/API/users/device2
Content-Type: application/json

{
  "groupname": "newgroup",
  "email": "prova1@example.com",
  "password": "password123456",
  "gender": "male",
  "height": 1.80,
  "weight": 75,
  "age": 28,
  "liftedweight": 90,
  "shiftduration": 420
}

// Now it's your turn to test your APIs as much as possible!